### ISSUE TITLE
Failed resolution of ActivityInvoker

### ISSUE THREAD

**Issue by Rawa** [mannodermaus/android-junit5#343]
Hey! Thanks for all the great work 🙏 

We updated some of our dependencies to the latest stable ones from `androidx.test` unfortunately it seems like the `createAndroidComposeExtension` doesn't play nice with it. I've also tried latest `1.5.0-SNAPSHOT` which had the same problem.

Any ideas?

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/internal/platform/app/ActivityInvoker$-CC;
at androidx.test.core.app.InstrumentationActivityInvoker.getIntentForActivity(Unknown Source:0)
at androidx.test.core.app.ActivityScenario.<init>(ActivityScenario.java:180)
at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:201)
at de.mannodermaus.junit5.compose.AndroidComposeExtensionKt$createAndroidComposeExtension$1.invoke(AndroidComposeExtension.kt:72)
at de.mannodermaus.junit5.compose.AndroidComposeExtensionKt$createAndroidComposeExtension$1.invoke(AndroidComposeExtension.kt:72)
at de.mannodermaus.junit5.compose.AndroidComposeExtension$use$1.invoke(AndroidComposeExtension.kt:130)
at de.mannodermaus.junit5.compose.AndroidComposeExtension$use$1.invoke(AndroidComposeExtension.kt:127)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.withDisposableContent(ComposeUiTest.android.kt:505)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:333)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withComposeIdlingResource(ComposeUiTest.android.kt:385)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withComposeIdlingResource(ComposeUiTest.android.kt:219)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1.invoke(ComposeUiTest.android.kt:332)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withWindowRecomposer(ComposeUiTest.android.kt:359)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withWindowRecomposer(ComposeUiTest.android.kt:219)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1.invoke(ComposeUiTest.android.kt:331)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:372)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:219)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:330)
at androidx.compose.ui.test.EspressoLink.withStrategy(EspressoLink.android.kt:66)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:329)
at androidx.compose.ui.test.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:155)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:328)
at androidx.compose.ui.test.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:146)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:327)
at de.mannodermaus.junit5.compose.AndroidComposeExtension.use(AndroidComposeExtension.kt:127)
at net.mullvad.mullvadvpn.compose.dialog.CreateCustomListDialogTest.givenNoErrorShouldShowNoErrorMessage(CreateCustomListDialogTest.kt:35)
at java.lang.reflect.Method.invoke(Native Method)
at java.util.ArrayList.forEach(ArrayList.java:1262)
at java.util.ArrayList.forEach(ArrayList.java:1262)
Suppressed: java.lang.IllegalStateException: Activity scenario could not be launched
at de.mannodermaus.junit5.compose.AndroidComposeExtension.getScenario(AndroidComposeExtension.kt:109)
at de.mannodermaus.junit5.compose.AndroidComposeExtension.afterEach(AndroidComposeExtension.kt:176)
... 2 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.test.internal.platform.app.ActivityInvoker$-CC" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~Ed7dGOh_iGj7fHpk_574Eg==/net.mullvad.mullvadvpn.test-hoRUtg04UPgwCH1SIGLJaA==/base.apk", zip file "/data/app/~~YiO21OyfoOpUuqo3OTnGGw==/net.mullvad.mullvadvpn-K0c694zsc4E45alKY4bWGA==/base.apk"],nativeLibraryDirectories=[/data/app/~~Ed7dGOh_iGj7fHpk_574Eg==/net.mullvad.mullvadvpn.test-hoRUtg04UPgwCH1SIGLJaA==/lib/arm64, /data/app/~~YiO21OyfoOpUuqo3OTnGGw==/net.mullvad.mullvadvpn-K0c694zsc4E45alKY4bWGA==/lib/arm64, /data/app/~~Ed7dGOh_iGj7fHpk_574Eg==/net.mullvad.mullvadvpn.test-hoRUtg04UPgwCH1SIGLJaA==/base.apk!/lib/arm64-v8a, /data/app/~~YiO21OyfoOpUuqo3OTnGGw==/net.mullvad.mullvadvpn-K0c694zsc4E45alKY4bWGA==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
... 29 more
```

**Comment by compscidr** [comment]
Also having this issue, have recently updated some androidx test dependencies - trying to narrow to which one exactly as it somehow snuck past my CI

**Comment by compscidr** [comment]
Okay, so narrowed to `androidx.test:monitor` - it works with `1.5.2`, but fails with both `1.6.0` and `1.6.1`

**Comment by mannodermaus** [comment]
Thanks for reporting and doing some of the detective work already, y'all! It seems like there is some binary incompatibility between AndroidX's `monitor:1.6.x` and `monitor:1.7.x`, and this transitive dependency fails with a missing class when loaded through `ActivityScenario`. I can see that both versions differ in the classes they pack:

|||
|---|---|
|<img width="800" alt="Screenshot 2024-07-22 at 9 59 49" src="https://github.com/user-attachments/assets/fd508a9e-4ec9-4280-8144-5391f7474c15">|<img width="800" alt="Screenshot 2024-07-22 at 10 00 06" src="https://github.com/user-attachments/assets/45deb05b-5fa3-4256-8b78-79c9b84cd7a6">|

The failure happens with a synthetic class (`ActivityInvoker$-CC`), which I suppose is present in 1.6, but absent in 1.7. The `android-test-compose` artifact being compiled against 1.6 probably expects that class to be there, then crashes when it isn't.

<img width="320" alt="Screenshot 2024-07-22 at 10 03 17" src="https://github.com/user-attachments/assets/d33a379d-afd3-4166-a075-a2ccae660e47">

Bumping the dependencies to the latest and greatest of `androidx.test` for the instrumentation libraries should be an easy fix, so let me get to this shortly. I'll ping here once the snapshots have been updated.

**Comment by Rawa** [comment]
@mannodermaus Thanks, and nice detective work! 

Is there any way we can avoid the false positive behavior if this issue occurs again? It is easy to miss since one have to look directly at the logs to detect this.

**Comment by mannodermaus** [comment]
@Rawa + @compscidr, thanks for your patience. The updated `1.5.0-SNAPSHOT` of the instrumentation test libraries is now available. Could you please check if the issue has indeed been resolved by me simply updating the dependencies? 🙇‍♂️ 

> Is there any way we can avoid the false positive behavior if this issue occurs again?

Nothing great that I can come up with from the end of this project, I'm afraid. Services like Dependabot to keep dependencies up-to-date in a semi-automatic fashion come to mind. Those would keep this project's snapshots tailored to the very latest of AndroidX at all times – I could look into that. Beyond that however, it's a bit outside the realm of possibilities of this repo to verify the integrity of all its transitive dependencies.

Maintaining binary compatibility is a task that seems to have gotten unintentionally messed up on the AndroidX side here. For android-junit5 (both the plugin and the instrumentation libraries), I verify binary compatibility across releases with a static analyzer (note the `api` folders in each module here). I was hoping that Google would employ something similar, but I suppose not.

**Comment by Rawa** [comment]
I quickly tried using the `1.5.0-SNAPSHOT`, it yielded the same result:

```
java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/internal/platform/app/ActivityInvoker$-CC;
	at androidx.test.core.app.InstrumentationActivityInvoker.getIntentForActivity(Unknown Source:0)
	at androidx.test.core.app.ActivityScenario.<init>(ActivityScenario.java:180)
	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:201)
	at net.mullvad.mullvadvpn.compose.ComposeRuleExtensionsKt.createEdgeToEdgeComposeExtension$lambda$1(ComposeRuleExtensions.kt:20)
	at net.mullvad.mullvadvpn.compose.ComposeRuleExtensionsKt.$r8$lambda$4loho9hgX84DzrD7G1i8RSitcMI(Unknown Source:0)
	at net.mullvad.mullvadvpn.compose.ComposeRuleExtensionsKt$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
	at de.mannodermaus.junit5.compose.AndroidComposeExtension$use$1.invoke(AndroidComposeExtension.kt:130)
	at de.mannodermaus.junit5.compose.AndroidComposeExtension$use$1.invoke(AndroidComposeExtension.kt:127)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.withDisposableContent(ComposeUiTest.android.kt:505)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:333)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withComposeIdlingResource(ComposeUiTest.android.kt:385)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withComposeIdlingResource(ComposeUiTest.android.kt:219)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1.invoke(ComposeUiTest.android.kt:332)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withWindowRecomposer(ComposeUiTest.android.kt:359)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withWindowRecomposer(ComposeUiTest.android.kt:219)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1.invoke(ComposeUiTest.android.kt:331)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:372)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:219)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:330)
	at androidx.compose.ui.test.EspressoLink.withStrategy(EspressoLink.android.kt:66)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:329)
	at androidx.compose.ui.test.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:155)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:328)
	at androidx.compose.ui.test.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:146)
	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:327)
	at de.mannodermaus.junit5.compose.AndroidComposeExtension.use(AndroidComposeExtension.kt:127)
	at net.mullvad.mullvadvpn.compose.screen.WelcomeScreenTest.testShowBillingPaymentAvailable(WelcomeScreenTest.kt:185)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.util.ArrayList.forEach(ArrayList.java:1613)
	at java.util.ArrayList.forEach(ArrayList.java:1613)
	Suppressed: java.lang.IllegalStateException: Activity scenario could not be launched
		at de.mannodermaus.junit5.compose.AndroidComposeExtension.getScenario(AndroidComposeExtension.kt:109)
		at de.mannodermaus.junit5.compose.AndroidComposeExtension.afterEach(AndroidComposeExtension.kt:176)
		... 2 more
```

Looking at the dependencies in Android Studio it seems like it slightly differs from what is being looked up:
![Screenshot 2024-07-22 at 16 28 35](https://github.com/user-attachments/assets/9d0840d6-489d-4b09-bebc-875e93114873)
The error shows:
`androidx/test/internal/platform/app/ActivityInvoker$-CC`
vs what I see in Android Studio:
`androidx/test/internal/platform/app/ActivityInvoker$$CC`

**Comment by Rawa** [comment]
Seems like my dependency tree for some reason keeps some of the old versions still though, not sure why. 

![Screenshot 2024-07-22 at 16 35 27](https://github.com/user-attachments/assets/60c00e02-8073-461a-aa43-c50a70f4ff33)

**Comment by mannodermaus** [comment]
Thanks for checking. You can verify the origin of unwanted dependencies via `./gradlew dependencies`, then grepping the output for e.g. `android-test-core:1.3.0`.

I'd wager that it's probably the android-junit5 plugin that insists on the older versions here, as it can automatically configure them for you if it detects JUnit 5 in the `androidTestImplementation` configuration. First of all, could you check that your plugin is using the latest version `1.10.0.0`? Second, could you tell the plugin to use the snapshot of the instrumentation test libraries, like so?

```kotlin
// In your app module's build.gradle.kts file:

junitPlatform {
  instrumentationTests.version = "1.5.0-SNAPSHOT"
}
```

**Comment by Rawa** [comment]
> Thanks for checking. You can verify the origin of unwanted dependencies via `./gradlew dependencies`, then grepping the output for e.g. `android-test-core:1.3.0`.
> 
> I'd wager that it's probably the android-junit5 plugin that insists on the older versions here, as it can automatically configure them for you if it detects JUnit 5 in the `androidTestImplementation` configuration. First of all, could you check that your plugin is using the latest version `1.10.2.0-SNAPSHOT`? Second, could you tell the plugin to use the snapshot of the instrumentation test libraries, like so?
> 
> ```kotlin
> // In your app module's build.gradle.kts file:
> 
> junitPlatform {
>   instrumentationTests.version = "1.5.0-SNAPSHOT"
> }
> ```

Hey, I just tested some more. I had missed to update the plugin to `1.10.2.0-SNAPSHOT`, this seems to have fixed the dependency chain. I now only see uses of `1.5.0-SNAPSHOT`.

```
./gradlew app:dependencies | grep "android-test-core"
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
\--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (n)
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:{strictly 1.5.0-SNAPSHOT} -> 1.5.0-SNAPSHOT (c)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:{strictly 1.5.0-SNAPSHOT} -> 1.5.0-SNAPSHOT (c)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:{strictly 1.5.0-SNAPSHOT} -> 1.5.0-SNAPSHOT (c)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:{strictly 1.5.0-SNAPSHOT} -> 1.5.0-SNAPSHOT (c)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
|    +--- de.mannodermaus.junit5:android-test-core:1.4.0 -> 1.5.0-SNAPSHOT
+--- de.mannodermaus.junit5:android-test-core:1.5.0-SNAPSHOT (*)
```

I also added the junitPlatform configuration according to your instructions, however I still see the same result in my output.

```
07-23 09:47:42.337  9661  9682 E TestRunner: ----- begin exception -----
07-23 09:47:42.337  9661  9682 E TestRunner: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/internal/platform/app/ActivityInvoker$-CC;
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.test.core.app.InstrumentationActivityInvoker.getIntentForActivity(Unknown Source:0)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.test.core.app.ActivityScenario.<init>(ActivityScenario.java:180)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:201)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at net.mullvad.mullvadvpn.compose.ComposeRuleExtensionsKt.createEdgeToEdgeComposeExtension$lambda$1(ComposeRuleExtensions.kt:20)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at net.mullvad.mullvadvpn.compose.ComposeRuleExtensionsKt.$r8$lambda$4loho9hgX84DzrD7G1i8RSitcMI(Unknown Source:0)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at net.mullvad.mullvadvpn.compose.ComposeRuleExtensionsKt$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at de.mannodermaus.junit5.compose.AndroidComposeExtension$use$1.invoke(AndroidComposeExtension.kt:130)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at de.mannodermaus.junit5.compose.AndroidComposeExtension$use$1.invoke(AndroidComposeExtension.kt:127)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.withDisposableContent(ComposeUiTest.android.kt:505)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:333)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withComposeIdlingResource(ComposeUiTest.android.kt:385)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withComposeIdlingResource(ComposeUiTest.android.kt:219)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1.invoke(ComposeUiTest.android.kt:332)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withWindowRecomposer(ComposeUiTest.android.kt:359)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withWindowRecomposer(ComposeUiTest.android.kt:219)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1.invoke(ComposeUiTest.android.kt:331)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:372)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:219)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:330)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.EspressoLink.withStrategy(EspressoLink.android.kt:66)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:329)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:155)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:328)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:146)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:327)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at de.mannodermaus.junit5.compose.AndroidComposeExtension.use(AndroidComposeExtension.kt:127)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at net.mullvad.mullvadvpn.compose.screen.OutOfTimeScreenTest.testClickRedeemVoucher(OutOfTimeScreenTest.kt:102)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at java.lang.reflect.Method.invoke(Native Method)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at java.util.ArrayList.forEach(ArrayList.java:1613)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at java.util.ArrayList.forEach(ArrayList.java:1613)
07-23 09:47:42.337  9661  9682 E TestRunner: 	Suppressed: java.lang.IllegalStateException: Activity scenario could not be launched
07-23 09:47:42.337  9661  9682 E TestRunner: 		at de.mannodermaus.junit5.compose.AndroidComposeExtension.getScenario(AndroidComposeExtension.kt:109)
07-23 09:47:42.337  9661  9682 E TestRunner: 		at de.mannodermaus.junit5.compose.AndroidComposeExtension.afterEach(AndroidComposeExtension.kt:176)
07-23 09:47:42.337  9661  9682 E TestRunner: 		... 2 more
07-23 09:47:42.337  9661  9682 E TestRunner: Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.test.internal.platform.app.ActivityInvoker$-CC" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~_XVLq8c73HcM91ZWW-EzxQ==/net.mullvad.mullvadvpn.test-tbwU6rr3nAqKcKRMgt_fkQ==/base.apk", zip file "/data/app/~~-i7W15lYC8EgvC8yhANkSw==/net.mullvad.mullvadvpn-dcvdYO3MZxoLBcqbrzlLmg==/base.apk"],nativeLibraryDirectories=[/data/app/~~_XVLq8c73HcM91ZWW-EzxQ==/net.mullvad.mullvadvpn.test-tbwU6rr3nAqKcKRMgt_fkQ==/lib/arm64, /data/app/~~-i7W15lYC8EgvC8yhANkSw==/net.mullvad.mullvadvpn-dcvdYO3MZxoLBcqbrzlLmg==/lib/arm64, /data/app/~~_XVLq8c73HcM91ZWW-EzxQ==/net.mullvad.mullvadvpn.test-tbwU6rr3nAqKcKRMgt_fkQ==/base.apk!/lib/arm64-v8a, /data/app/~~-i7W15lYC8EgvC8yhANkSw==/net.mullvad.mullvadvpn-dcvdYO3MZxoLBcqbrzlLmg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
07-23 09:47:42.337  9661  9682 E TestRunner: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
07-23 09:47:42.337  9661  9682 E TestRunner: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
07-23 09:47:42.337  9661  9682 E TestRunner: 	... 30 more
07-23 09:47:42.337  9661  9682 E TestRunner: ----- end exception -----
07-23 09:47:42.339  9661  9682 I TestRunner: finished: testClickRedeemVoucher(net.mullvad.mullvadvpn.compose.screen.OutOfTimeScreenTest)

java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/test/internal/platform/app/ActivityInvoker$-CC;
at androidx.test.core.app.InstrumentationActivityInvoker.getIntentForActivity(Unknown Source:0)
at androidx.test.core.app.ActivityScenario.<init>(ActivityScenario.java:180)
at androidx.test.core.app.ActivityScenario.launch(ActivityScenario.java:201)
at net.mullvad.mullvadvpn.compose.ComposeRuleExtensionsKt.createEdgeToEdgeComposeExtension$lambda$1(ComposeRuleExtensions.kt:20)
at net.mullvad.mullvadvpn.compose.ComposeRuleExtensionsKt.$r8$lambda$4loho9hgX84DzrD7G1i8RSitcMI(Unknown Source:0)
at net.mullvad.mullvadvpn.compose.ComposeRuleExtensionsKt$$ExternalSyntheticLambda1.invoke(D8$$SyntheticClass:0)
at de.mannodermaus.junit5.compose.AndroidComposeExtension$use$1.invoke(AndroidComposeExtension.kt:130)
at de.mannodermaus.junit5.compose.AndroidComposeExtension$use$1.invoke(AndroidComposeExtension.kt:127)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$AndroidComposeUiTestImpl.withDisposableContent(ComposeUiTest.android.kt:505)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1$1.invoke(ComposeUiTest.android.kt:333)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withComposeIdlingResource(ComposeUiTest.android.kt:385)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withComposeIdlingResource(ComposeUiTest.android.kt:219)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1$1.invoke(ComposeUiTest.android.kt:332)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withWindowRecomposer(ComposeUiTest.android.kt:359)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withWindowRecomposer(ComposeUiTest.android.kt:219)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1$1.invoke(ComposeUiTest.android.kt:331)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.withTestCoroutines(ComposeUiTest.android.kt:372)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.access$withTestCoroutines(ComposeUiTest.android.kt:219)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1$1.invoke(ComposeUiTest.android.kt:330)
at androidx.compose.ui.test.EspressoLink.withStrategy(EspressoLink.android.kt:66)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1$1.invoke(ComposeUiTest.android.kt:329)
at androidx.compose.ui.test.IdlingResourceRegistry.withRegistry(IdlingResourceRegistry.jvm.kt:155)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment$runTest$1.invoke(ComposeUiTest.android.kt:328)
at androidx.compose.ui.test.ComposeRootRegistry.withRegistry(ComposeRootRegistry.android.kt:146)
at androidx.compose.ui.test.AndroidComposeUiTestEnvironment.runTest(ComposeUiTest.android.kt:327)
at de.mannodermaus.junit5.compose.AndroidComposeExtension.use(AndroidComposeExtension.kt:127)
at net.mullvad.mullvadvpn.compose.screen.OutOfTimeScreenTest.testClickRedeemVoucher(OutOfTimeScreenTest.kt:102)
at java.lang.reflect.Method.invoke(Native Method)
at java.util.ArrayList.forEach(ArrayList.java:1613)
at java.util.ArrayList.forEach(ArrayList.java:1613)
Suppressed: java.lang.IllegalStateException: Activity scenario could not be launched
at de.mannodermaus.junit5.compose.AndroidComposeExtension.getScenario(AndroidComposeExtension.kt:109)
at de.mannodermaus.junit5.compose.AndroidComposeExtension.afterEach(AndroidComposeExtension.kt:176)
... 2 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.test.internal.platform.app.ActivityInvoker$-CC" on path: DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/system/framework/android.test.mock.jar", zip file "/system/framework/android.test.base.jar", zip file "/data/app/~~_XVLq8c73HcM91ZWW-EzxQ==/net.mullvad.mullvadvpn.test-tbwU6rr3nAqKcKRMgt_fkQ==/base.apk", zip file "/data/app/~~-i7W15lYC8EgvC8yhANkSw==/net.mullvad.mullvadvpn-dcvdYO3MZxoLBcqbrzlLmg==/base.apk"],nativeLibraryDirectories=[/data/app/~~_XVLq8c73HcM91ZWW-EzxQ==/net.mullvad.mullvadvpn.test-tbwU6rr3nAqKcKRMgt_fkQ==/lib/arm64, /data/app/~~-i7W15lYC8EgvC8yhANkSw==/net.mullvad.mullvadvpn-dcvdYO3MZxoLBcqbrzlLmg==/lib/arm64, /data/app/~~_XVLq8c73HcM91ZWW-EzxQ==/net.mullvad.mullvadvpn.test-tbwU6rr3nAqKcKRMgt_fkQ==/base.apk!/lib/arm64-v8a, /data/app/~~-i7W15lYC8EgvC8yhANkSw==/net.mullvad.mullvadvpn-dcvdYO3MZxoLBcqbrzlLmg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
at java.lang.ClassLoader.loadClass(ClassLoader.java:637)
at java.lang.ClassLoader.loadClass(ClassLoader.java:573)
... 30 more```

I've also attached to output of `./gradlew app:dependencies`
[dependencies.txt](https://github.com/user-attachments/files/16345407/dependencies.txt)

**Comment by compscidr** [comment]
Sorry for the delay in getting back, I tried with the updated plugin and 1.5.0-snapshot on my end and it appears to be working on my end. Perhaps there is a caching issue with your build. I noticed when I was trying to reproduce the issue previously, as you play with the dependency versions, if you don't explicitly rebuild the test, it may still use an older build with the last dependency version.

**Comment by Rawa** [comment]
> Sorry for the delay in getting back, I tried with the updated plugin and 1.5.0-snapshot on my end and it appears to be working on my end. Perhaps there is a caching issue with your build. I noticed when I was trying to reproduce the issue previously, as you play with the dependency versions, if you don't explicitly rebuild the test, it may still use an older build with the last dependency version.
> 
> Also, it appears whatever fixed this, may have also fixed: https://github.com/mannodermaus/android-junit5/issues/338 - as I'm no longer having this issue any longer.

Ah yeah that could be a culprit, I'll try again tomorrow 👍

**Comment by Rawa** [comment]
Tested it again today. It didn't work on the same branch as I worked on yesterday, however when I tested on top of our latest where we updated other dependencies I got it to work. So probably some other dependency interfered somehow, not exactly sure what the cause was yet. So seems like the fix is good! 👍 Would you mind creating new stable release? @mannodermaus

**Comment by mannodermaus** [comment]
That dependency chain uncovered an issue with the POM packaging of transitive dependencies, thanks for pointing that out! I've just released plugin 1.10.2.0, which configures instrumentation 1.5.0 automatically. You should be able to remove your direct dependencies on `android-test-core`, `android-test-runner` and `android-test-compose` and it should still work after a Gradle sync. Cheers!

**Comment by Rawa** [comment]
https://developer.android.com/jetpack/androidx/releases/test#monitor-1.7.2 👀 
> Fix ActivityInvoker$-CC ClassNotFoundErrors when used with older androidx.test:core

**Comment by mannodermaus** [comment]
That sounds very promising. 👀 I'll update the dependency for the next snapshot.
